# Generated by Django 3.2.6 on 2021-08-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='card_img',
            field=models.ImageField(blank=True, null=True, upload_to='blog/card_img/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='blog/banner_img/'),
        ),
    ]
