# Generated by Django 3.2.6 on 2021-08-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210813_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='blog/banner_img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='card_img',
            field=models.ImageField(blank=True, null=True, upload_to='blog/card_img'),
        ),
    ]
