# Generated by Django 3.2.6 on 2021-08-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210813_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_published']},
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateField(),
        ),
    ]
